#+title: Scratch

* Задание
Построить синтаксический анализатор, который, принимая на входе текст на входном
языке, строит для него абстрактное синтаксическое дерево.

Грамматика входного языка должна быть описана в РБНФ с учётом приоритета и
ассоциативности операций. Синтаксический анализатор должен быть написан при
помощи методики рекурсивного спуска.

#+begin_src
/* Декартово произведение */
CartProd {
  (t.X e.X) (e.Y) = <CartProd-Bind t.X e.Y> <CartProd (e.X) (e.Y)>;
  (/* пусто */) (e.Y) = /* пусто */;
}

CartProd-Bind {
  t.X t.Y e.Y = (t.X t.Y) <CartProd-Bind t.X e.Y>;
  t.X /* пусто */ = /* пусто */;
}

/*
  Прибавление 1 к строковой записи числа:
  123 → 124, 99 → 100, 007 → 008
*/
Inc {
  e.Prefix s.Last, '0123456789' : e.1 s.Last s.Next e.2 = e.Prefix s.Next;
  e.Prefix '9' = <Inc e.Prefix> '0';
  /* пусто */ = '1';
}

/* Функция возвращает уникальные идентификаторы с заданным префиксом */
NextId {
  e.prefix
    , <Dg counter>
    : {
        s.n = e.prefix <Symb s.n> <Br counter '=' <Add 1 s.n>>;
        /* пусто */ = <Br counter '=' 0> <NextId e.prefix>;
      };
}
#+end_src

Чистый и на функциональном языке

* [ ] Составление абстрактного синтаксиса языка.
* [ ] Составление лексической структуры и конкретного синтаксиса языка в LL(1) РБНФ.
* [ ] Описание абстрактного синтаксического дерева при помощи типов данных выбранного студентом языка реализации.
* [ ] Написание лексического анализатора (можно использовать любой из ранее рассмотренных способов).
* [ ] Написание синтаксического анализатора методом рекурсивного спуска.
