#+title: Scratch

* [X] Исправить грамматику для вложенных указателей
* [ ] Дополнение абстрактного синтаксического дерева служебной информацией
(типы выражений, координаты для потенциально ошибочных конструкций).
* [ ] Расширение парсера для сохранения координат в синтаксическом дереве.
* [ ] Реализация классов исключений для семантических ошибок.
* [ ] Реализация семантической проверки как методов узлов семантического дерева.

Для корректных входных данных должно выводиться сообщение «Программа корректна»,
для некорректных — выдача координаты и описания первой семантической ошибки.

Посмотреть, какую область видимости имеет вложенное объявление enum

* Проверки:

- [ ] Используемые идентификаторы должны быть определены выше по тексту.
- [ ] Теги структур, теги перечислений и теги объединений не должны повторяться.
- [ ] enum’ы определяют глобальные константы, они тоже не должны повторяться.
- [ ] В структурах и объединениях не могут встречаться одноимённые поля.

* Результат:

- [ ] Программа должна выводить на экран значения всех констант.
- [ ] Для каждого типа должен вычисляться его объём. Считаем, что размеры целых
  чисел и перечислимых типов — 4 байта, вещественных чисел — 8 байт, размер
  указателя 4 байта. Считаем, что выравнивание не используется.
